### ISSUE TITLE
[Documentation] 更明显的更新文档引导

### ISSUE THREAD

**Issue by wibus-wee** [mx-space/docs-v2-legacy#36]
<sup>
Thank you for your contribution to the document. But it conflicts with existing content. I will not consider merging.
</sup>

<sup>
> Maybe what you want is a **more obvious update document guidance**, which will be gradually optimized in the future.

_Originally posted by @wibus-wee in https://github.com/mx-space/docs/issues/32#issuecomment-1783989803_
</sup>

**Comment by wibus-wee** [comment]
目前考虑的是引入一个链接直接引导过去，不知道 @wuhang2003 你觉得怎么样

**Comment by wuhang2003** [comment]
> 目前考虑的是引入一个链接直接引导过去，不知道 @wuhang2003 你觉得怎么样

我觉得行（
