### ISSUE TITLE
[Documentation] 补充系统要求

### ISSUE THREAD

**Issue by wibus-wee** [mx-space/docs-v2-legacy#41]
目前文档遗漏了对系统要求的相关内容，这将导致有可能不符合要求的用户安装后出现问题或无法安装

**Comment by wuhang2003** [comment]
> 目前文档遗漏了对系统要求的相关内容，这将导致有可能不符合要求的用户安装后出现问题或无法安装

@wibus-wee ~~我没记错的话就 Kami 文档简单提了个内核不小于 4.19，现在是把这个要求放得明显点是么？~~
1. 这个安装系统要求是需要丢在 引言（docs/index.md）还是丢在 Docker 部署（docs/docker.md）？
2. 关于硬件的最低要求（说的就是内存）要不要也一并加上？

**Comment by wibus-wee** [comment]
@wuhang2003 我想想吧，我到时候先建个分支做一点先？

**Comment by wibus-wee** [comment]
@wuhang2003 我写了一点，但是不知道还有啥要加的（悲）您看看还要加点什么吧

**Comment by wuhang2003** [comment]
@wibus-wee 除了 Disk 那一行有点怪怪的之外剩下应该没啥加的了（

**Comment by wibus-wee** [comment]
@wuhang2003 那改完之后你直接提PR罢（

**Comment by wuhang2003** [comment]
彳亍（

**Comment by wuhang2003** [comment]
@wibus-wee 丢 PR 了，来修 CI 吧（
