### ISSUE TITLE
调整 `EnvVariableConfig`

### ISSUE THREAD

**Issue by wuhang2003** [mx-space/docs-v2-legacy#69]
基于 #68 
Docker 部署页面所提供的 `EnvVariableConfig` 仍需要进行微调而无法像原来那样直接保存，需要进行调整

**Comment by wibus-wee** [comment]
我没太明白这个是什么意思

“直接保存” 是什么情况？我记得我写的是复制到黏贴版的来着

**Comment by wuhang2003** [comment]
指的是原来复制到剪贴板粘贴到文件后可以直接保存 .env 文件
而现在多一个调整格式的步骤（即每一行前面加 `-` 和调整缩进）

**Comment by wibus-wee** [comment]
🤔 缩进可能做不好

哦原来是变成了 YAML format 啊😂 我的错

**Comment by wibus-wee** [comment]
<img width="488" alt="image" src="https://github.com/mx-space/docs/assets/62133302/4c25772d-6290-4c8f-8ef0-4c25e8eb223f">

**Comment by wuhang2003** [comment]
@wibus-wee 参考格式有问题，故重新打开此 issues（~~我咋忘了检查了呢~~
以下为参考
```yaml
      - ALLOWED_ORIGINS=domains
      - JWT_SECRET=your_secret
      - ENCRYPT_ENABLE=false
      - ENCRYPT_KEY=
 ```

**Comment by wibus-wee** [comment]
Fixed. 我的错😭 我一下子记错了YAML的格式
